name: RenderCV CI

on:
  push:
    branches: ["main"]
    paths:
      - "*cv.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "*cv.yaml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14.3
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.3"
          pip-version: "26.1.2"
      - name: Install RenderCV
        run: pip install "rendercv[full]==2.8"

      - name: Pip Cache
        uses: actions/cache@v6
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/rendercv.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Render Spanish CV
        run: rendercv render juan_bermudez_es_cv.yaml
      - name: Render English CV
        run: rendercv render juan_bermudez_cv.yaml
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            juan_bermudez_cv.pdf
            juan_bermudez_es_cv.pdf
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Automated release for PDF generated from CV YAML files.
